#!/bin/bash
#This script will act as a program running vlc on the selected disc drive
#Once the program is open, it will then be in interactive mode

echo "#THE CONVENIENCE CONTAINER#
#This bash script runs programs that are commonly ran on most ubuntu/linux systems with the most useful options#
#Xubuntu is the preferred system, but it can be ran on other variants of ubuntu and debian#
#It runs system updates, media players, opens and closes DVD/CD-ROM drives, and restarts and ends the system#
#Annual updates and patches will be applied if needed#
#This script has been developed and is maintained by the Author Istimsak Abdulbasir#
#This script can be used or modified to fit your personal needs#


#The list below are all convenience scripts plycon runs

#play VlC#			    #Install packages from repository
playvlc				      apinstall
#Update ubuntu#			#open the DVD/CD-ROM#
update_ubuntu			  openmedia
#shutdown#			    #examine the mounted partition#
endsystem			      exdisk
#Restart#			      #create a rsa ssh key
systemrestart 			sshkey
#Test the speed of your internet connection bidirectional#
speedtest-cli"

echo "pick a convienience script to run"

read x

$x

#end
