#!/bin/bash

#This script shows the time and date of the running system
#users who are currently logged in,
#and, how long the system as been running

echo "Checking system uptime"

#This command shows the current date
#The output of the command ("1", which means stdout) is redirected to file variable $UPTIME
echo "Current date and time"
date

#This command displays the current day of the year, if accurate
#The special character (+%j) tells date to display the day of the year
echo "Number of day in the year"
date

#This command lists all current users logged on the system
echo "Current people looged in"
who

#This command displays the time the system has been running
echo "How long has this system been running"
uptime

exit 0
